### ISSUE TITLE
`hugo serve` uses 3 GB when serving archive

### ISSUE THREAD

**Issue by mpsijm** [WISVCH/chipcie-website#22]
`hugo serve` uses 3 GB since we added the archive (#15), which I think is somewhat undesirable :stuck_out_tongue: It also takes a bit longer to start.
We should figure out if there is a way for `hugo` to serve static files without having it keep them in memory all the time.

There is the `--renderStaticToDisk` flag (see [options](https://gohugo.io/commands/hugo_server/#options)), which copies the entire `/static` folder (including the archive) to `/public` before serving. Still somewhat undesirable, but already better than keeping everything in memory, I guess?

Apparently, someone had the same question [in 2019](https://discourse.gohugo.io/t/do-not-copy-static-files-to-memory-nor-disk/20604), but they never got an answer.

**Comment by mpsijm** [comment]
Possibly, a symlink from `/static` to `/public` could work, in combination with the `--renderStaticToDisk` flag: https://github.com/gohugoio/hugo/issues/7591#issuecomment-678755857

**Comment by mpsijm** [comment]
A [similar Q&A](https://discourse.gohugo.io/t/how-to-deal-with-large-amount-of-resource-files-outside-hugos-dir-sturcture/22273) got as answer "yeah, just don't serve them from Hugo, but store them externally". So, one other solution could be to not serve the archive via Hugo, but have a `python3 -m http.server` (or something similar) for the `/archive` subroutes (or possibly even for all static files). @verwoerd @robertdijk what do you think of that idea?

**Comment by robertdijk** [comment]
Hugo serve is only used locally when working on the site, but when we deploy it, we will just just Hugo to build it, and use nginx to serve it. So it’s not really a problem outside of the development.

**Comment by mpsijm** [comment]
Cool, good to know! Then running `hugo serve --renderStaticToDisk` in combination with symlinking `/static` to `/public` will work for me. I'll add it to the `README` :slightly_smiling_face:
